version: '2.4'

services:
  ## TOOLS
  # Nginx proxy manager to handle multiple services in 1 machine
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/pi/home-server/data:/data
      - /home/pi/home-server/letsencrypt:/etc/letsencrypt
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      netv4v6:
        ipv4_address: 172.19.0.7
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  ## SERVICES
  # PiHole: AdBlocking DNS service
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '82:80/tcp'
    volumes:
      - '/home/pi/home-server/etc-pihole:/etc/pihole'
      - '/home/pi/home-server/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    environment:
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      ServerIP: 192.168.1.53
      ServerIPv6: ${RBP_IPV6}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_URL}
      VIRTUAL_PORT: 80
      DNSSEC: "true"
      IPv6: "true"
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      netv4v6:
        ipv4_address: 172.19.0.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Bitwarden: password manager
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    ports:
      - '83:80'
      - '3012:3012'
    volumes:
      - /home/pi/home-server/vw-data/:/data
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      netv4v6:
        ipv4_address: 172.19.0.3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Wireguard: efficient VPN
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=${WIREGUARD_URL}
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=172.19.0.2
      - LOG_CONFS=true
    volumes:
      - /home/pi/home-server/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    networks:
      netv4v6:
        ipv4_address: 172.19.0.5

  # # NextCloud: Home Cloud - NAS
  # nextcloud:
  #   image: nextcloud/all-in-one:latest-arm64
  #   container_name: nextcloud-aio-mastercontainer
  #   environment:
  #     - TZ=Europe/Paris
  #     - APACHE_PORT=11000
  #     - NEXTCLOUD_UPLOAD_LIMIT=10G
  #     - APACHE_IP_BINDING=0.0.0.0
  #     - NEXTCLOUD_DATADIR=/mnt/raid/nextcloud
  #     - NEXTCLOUD_MOUNT=/mnt/
  #   volumes:
  #     - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0
  #   networks:
  #     netv4v6:
  #       ipv4_address: 172.19.0.4

  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /home/pi/home-server/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/"]
      interval: 30s
      timeout: 10s
      retries: 3

## NETWORK CONFIG
networks:
  netv4v6:
    name: netv4v6
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
          ip_range: 172.20.5.0/24
        - subnet: fdbc:6331:bae8::/48
          gateway: fdbc:6331:bae8::1

## VOLUMES CONFIG
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer