esphome:
  name: eps-led-biblio
  friendly_name: eps-led-biblio

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "r48Nrk2zPS5X2Gcd7KQyiYlgsBMuNuLI6Q80hyApaQU="

ota:
  password: "3805123c27e96f45d6925795334ccc49"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eps-Led-Biblio Fallback Hotspot"
    password: "ZZE5VnBYY4PB"

binary_sensor:
  # statut
  - platform: status
    name: "Statut"

sensor:
  # Qualité du signal
  - platform: wifi_signal
    name: "Signal Wifi"
    update_interval: 60s

  # Temps de fonctionnement
  - platform: uptime
    name: "Allumé depuis (s)"
    id: uptime_sec
       
switch:
# Bouton de redémarrage
  - platform: restart
    name: "Redémarrage"

# Transformation des secondes en jours
text_sensor:
  - platform: template
    name: "Allumé depuis (j)"
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };          
    icon: mdi:clock-start
    update_interval: 60s
    